import logging
import os
import re
from datetime import datetime, timezone

import redis.asyncio as redis

logger = logging.getLogger("crs-tuner.exclusions")

REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")
FP_THRESHOLD = int(os.environ.get("AI_TUNER_FP_THRESHOLD", "3"))
CONFIDENCE_MIN = float(os.environ.get("AI_TUNER_CONFIDENCE_MIN", "0.7"))
EXCLUSIONS_DIR = os.environ.get("EXCLUSIONS_DIR", "/etc/coraza-exclusions")
# Reserved range for crs-tuner's own generated rules — see
# coraza-service/crs-exclusions/crs_exclusion.conf's header for the full
# three-way split (crs-extra/, hand-written exclusions, this).
AUTO_ID_START = 60000

_client: redis.Redis | None = None


def get_client() -> redis.Redis:
    global _client
    if _client is None:
        _client = redis.from_url(REDIS_URL, decode_responses=True)
    return _client


def _safe_domain(domain: str) -> str:
    """auto-<domain>.conf filename — strip anything that isn't a sane
    hostname character, since domain comes from a client-controlled Host
    header (via scoring-service) and this becomes a filesystem path."""
    return re.sub(r"[^a-zA-Z0-9.-]", "_", domain) or "unknown"


async def _next_auto_id() -> int:
    client = get_client()
    # SETNX seeds the counter once, idempotently, so concurrent callers never
    # race on "is this the first ID ever assigned" — plain INCR after that
    # always returns a fresh, unique, sequential ID starting at AUTO_ID_START.
    await client.setnx("crs-tuner:next-auto-id", AUTO_ID_START - 1)
    return await client.incr("crs-tuner:next-auto-id")


async def record_verdict(*, domain: str, path: str, rule_id: str, variable: str, key: str, verdict: dict) -> bool:
    """Threshold-gated: only a *repeated* false-positive verdict for the same
    (domain, path, rule, variable, key) combination generates an exclusion —
    not a single call, bounding the blast radius of one bad judgment, and
    narrower than domain alone: a false positive observed on one endpoint
    doesn't get generalized to every path on the domain. Idempotent: once
    generated for a combo, further matches don't regenerate it. Returns
    whether an exclusion was (newly) written, for logging at the call site."""
    if verdict.get("verdict") != "false_positive" or verdict.get("confidence", 0.0) < CONFIDENCE_MIN:
        return False

    combo = f"{domain}:{path}:{rule_id}:{variable}:{key}"
    generated_key = f"crs-tuner:generated:{combo}"

    client = get_client()
    if await client.get(generated_key):
        return False

    count = await client.incr(f"crs-tuner:fp-count:{combo}")
    if count < FP_THRESHOLD:
        return False

    await _write_exclusion(domain=domain, path=path, rule_id=rule_id, variable=variable, key=key, verdict=verdict, count=count)
    await client.set(generated_key, "1")
    return True


async def _write_exclusion(*, domain: str, path: str, rule_id: str, variable: str, key: str, verdict: dict, count: int) -> None:
    new_id = await _next_auto_id()
    filename = os.path.join(EXCLUSIONS_DIR, f"auto-{_safe_domain(domain)}.conf")
    target = f"{variable}:{key}" if key else variable
    header = (
        f"# Auto-generated by crs-tuner {datetime.now(timezone.utc).isoformat()}\n"
        f"# Rule {rule_id} judged a false positive {count} times for {domain}{path} on {target}.\n"
        f"# Last reasoning: {verdict.get('reasoning', '')}\n"
    )
    if path:
        # REQUEST_FILENAME, not REQUEST_URI — path only, no query string, so
        # the same endpoint hit with different query params still matches.
        # chain: the Host condition alone isn't the scope here, the pair is
        # — narrower than a domain-wide exclusion (Part 3/4 of the original
        # plan only scoped by domain; this is deliberately tighter).
        rule = (
            f'SecRule REQUEST_HEADERS:Host "@streq {domain}" \\\n'
            f'    "id:{new_id},phase:1,pass,nolog,chain"\n'
            f'    SecRule REQUEST_FILENAME "@streq {path}" \\\n'
            f'        "ctl:ruleRemoveTargetById={rule_id};{target}"\n\n'
        )
    else:
        rule = (
            f'SecRule REQUEST_HEADERS:Host "@streq {domain}" \\\n'
            f'    "id:{new_id},phase:1,pass,nolog,ctl:ruleRemoveTargetById={rule_id};{target}"\n\n'
        )
    with open(filename, "a") as f:
        f.write(header + rule)
    logger.info("wrote auto-exclusion id=%d domain=%s path=%s rule=%s target=%s", new_id, domain, path, rule_id, target)
